# Generated by Django 6.0.5 on 2026-05-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                ("apellido", models.CharField(max_length=100, verbose_name="Apellido")),
                ("biografia", models.TextField(blank=True, verbose_name="Biografía")),
                (
                    "nacionalidad",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nacionalidad"
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="autores/", verbose_name="Foto"
                    ),
                ),
            ],
            options={
                "verbose_name": "Autor",
                "verbose_name_plural": "Autores",
                "ordering": ["apellido", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6c757d",
                        help_text="Color en formato HEX, ej: #FF5733",
                        max_length=7,
                        verbose_name="Color",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Libro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=300, verbose_name="Título")),
                (
                    "isbn",
                    models.CharField(max_length=20, unique=True, verbose_name="ISBN"),
                ),
                (
                    "editorial",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Editorial"
                    ),
                ),
                (
                    "anio_publicacion",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Año de publicación"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "portada",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="portadas/",
                        verbose_name="Portada",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("prestado", "Prestado"),
                            ("reservado", "Reservado"),
                            ("mantenimiento", "En mantenimiento"),
                        ],
                        default="disponible",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("fisico", "Físico"), ("digital", "Digital")],
                        default="fisico",
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "cantidad_ejemplares",
                    models.IntegerField(
                        default=1, verbose_name="Cantidad de ejemplares"
                    ),
                ),
                (
                    "ejemplares_disponibles",
                    models.IntegerField(
                        default=1, verbose_name="Ejemplares disponibles"
                    ),
                ),
                (
                    "fecha_adquisicion",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de adquisición"
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Ubicación en biblioteca",
                    ),
                ),
                (
                    "autores",
                    models.ManyToManyField(
                        related_name="libros",
                        to="catalogo.autor",
                        verbose_name="Autores",
                    ),
                ),
                (
                    "categorias",
                    models.ManyToManyField(
                        related_name="libros",
                        to="catalogo.categoria",
                        verbose_name="Categorías",
                    ),
                ),
            ],
            options={
                "verbose_name": "Libro",
                "verbose_name_plural": "Libros",
                "ordering": ["titulo"],
            },
        ),
    ]
